- ALL DSA PATTERNS BY STRIVER.pdf
Striver All DSA pattern for Interview
> Striver DSA pattern for Interview

- ZCOSCH.cpp
> added a solution for codechef problem

- longest_palindrome_substring.cpp
Hey, This is my first contribution to open source. Thank you for this opportunity :D
> Longest Palindromic Substring #31

- Dynamic Programming/Unbounded_Knapsack.cpp
> More Solutions

- 48_Rotate_image.cpp
> one file add

- palindrome.cpp
plaindrome number in c plus plus programming language.
> Palindrome number in cpp

- index.html
> added a simple html page

- website.html
> Created website with html CSS

- Create a simple Html page/index.html
This pull request solves issue #55
> Added html webpage

- Searching/TernarySearch.py
- Searching/Ternary_search.cpp
Please add my file for hocktober fest 2022
> TernarySearch

- MaxSubArray.py
@shubham7668 
Added python solution for Max Sub Array problem
> MaxSubArray.py

- 3 sum in Python
it solve issues #88 
Plz merge it.
> Create 3 sum in Python

- LinkedListCycle.py
Hey,
This is my first time in Hacktober so there may be some mistakes, if there is please tell me ill correct them. i have added python code for the program.
Thanks.
> Added Code for Linked List Cycle Python

- Dynamic Programming/Frog 1 - At coder DP set
its in python and it consider as good question of DP
> Create Frog 1 - At coder DP set

- portfolio.html
Issue URL: https://github.com/shubham7668/hacktober/issues/84
> Portfolio Website using HTML

- Max_SubArray.py
> Max Sub Array

- Implement Trie (Prefix Tree) in python issue
> Create Implement Trie (Prefix Tree) in python

- Whole Info about Hashing/183aryan.md
In this file, I have tried to put all the information related to Hashing, Hash function, Collision resolution techniques along with suitable example at one place. After reading the whole documentation any one can easily relate everything about hashing and its different aspects. This file is very useful for those who are preparing for placements, higher studies as Hashing is very important topic in Data structures.
> Info related to Hashing.

- valid parenthesis.py
Please check valid parenthesis.py file and check the code if its working
Its my first open source contribution so if any changes to be made I would be happy to change it . 
Hoping this request is accepted
> Valid Parenthesis Code 

- Longest_Substring_without_Repeating_Characters.py
I would like to request the maintainer(s) to accept this PR as a part of the hacktoberfest 2022, and also label my PR as a hacktoberfest. Thank You!
> Code for Longest Substring without Repeating Characters in python added

- matrixChainMultiplication/183aryan.md
In this file, I have added a famous dynamic programming question named MCM with solution code in JAVA.
> This file contain solution to MCM DP Q in JAVA.

- Create a simple Html page/Register.html
> Register page in html css

- Countdown_timer.html
Followed and Starred Repo, No errors.
> Created a Countdown Timer using JS

- DiscordTimestampMaker/generator.js
- DiscordTimestampMaker/index.html
- DiscordTimestampMaker/style.css
Implemented as a basic HTML/CSS/JS web page with form input to generate Discord timestamp strings in a variety of formats. Should look like this, basically: [https://alexholderdeveloper.github.io/DiscordTimestampGenerator/src/index.html](https://alexholderdeveloper.github.io/DiscordTimestampGenerator/src/index.html)
> Discord timestamp generator

- wifiAutoConenctor.py
Created a Wifi AutoConnector using Python
> Created a Wifi AutoConnector using Python

- Graph/BFS-breadth-first-search.cpp
- Graph/DFS-depth-first-search.cpp
- Graph/UnionFind/number-of-provinces.cpp
- Graph/UnionFind/redundant-connection.cpp
- Graph/bellman-ford-algorithm.cpp
- Graph/cheapest-flight-with-k-stops.cpp
- Graph/course-schedule-1-or-deadlock-detection.cpp
- Graph/detect-cycle-directed-graph.cpp
- Graph/detect-cycle-undirected-graph.cpp
- Graph/dijkstras-algorithm.cpp
- Graph/disjoint-sets-optimized.cpp
- Graph/disjoint-sets.cpp
- Graph/euler-circuit-and-path.cpp
- Graph/flood-fill.cpp
- Graph/floyd-warshall-algorithm.cpp
- Graph/kosaraju-algorithm.cpp
- Graph/kruskals-algorithm.cpp
- Graph/network-delay-time.cpp
- Graph/num-operations-to-connect-network.cpp
- Graph/number-of-islands.cpp
- Graph/prims-algorithm.cpp
- Graph/print-adjacency-list.cpp
- Graph/rat-in-a-maze.cpp
- Graph/topological-sort.cpp
Basic dsa questions realted to graphs
> Added questions related to graphs

- Joke Generator/index.html
> ADD: Joke Generator

- Create a simple Html page/Next_Greater_Element.html
Created a Question Answer HTML page
Please add my file for Hacktober fest 2022
> Next greater element Question Answer HTML page

- crud/CRUD.css
- crud/CRUD.html
- crud/CRUD.js
> Added a crud application using Html,css,js

- Registration_form_html_css/form.html
- Registration_form_html_css/style.css
- Registration_form_html_css/thanks.html
Kindly merge this project for hacktoberfest
> Merge this Registration Form built using html and css
